name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.2.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
      - name: Install gems
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
